// <auto-generated />
using System;
using System.Collections.Generic;
using Library_BookAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Library_BookAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231003215028_addBookss")]
    partial class addBookss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Library_BookAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<string>("Borrower")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YearPublished")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J.K. Rowling",
                            AverageRating = 1.5,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 2, 21, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "The first book in the Harry Potter series, where young Harry discovers his magical heritage.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Fantasy",
                            ISBN = "978-0747532743",
                            ImageUrl = "https://m.media-amazon.com/images/I/91AbRwk2S0L._SL1500_.jpg",
                            IsAvailable = false,
                            Language = "English",
                            Location = "Shelf 8, Row 2",
                            PageCount = 299,
                            Publisher = "Bloomsbury Publishing",
                            Tags = new List<string> { "Magic", "Wizardry", "Adventure" },
                            Title = "Harry Potter and the Philosopher's Stone",
                            UpdatedDate = new DateTime(2022, 11, 28, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1998
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.K. Rowling",
                            AverageRating = 0.59999999999999998,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 10, 2, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "The second book in the Harry Potter series, where Harry returns to Hogwarts amidst mysterious attacks.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Fantasy",
                            ISBN = "978-0439064873",
                            ImageUrl = "https://static.wikia.nocookie.net/harrypotter/images/1/17/Chamberofsecrets.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 4, Row 9",
                            PageCount = 258,
                            Publisher = "Bloomsbury Publishing",
                            Tags = new List<string> { "Magic", "Wizardry", "Adventure" },
                            Title = "Harry Potter and the Chamber of Secrets",
                            UpdatedDate = new DateTime(2023, 2, 19, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1999
                        },
                        new
                        {
                            Id = 3,
                            Author = "J.K. Rowling",
                            AverageRating = 4.5,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 2, 21, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "The third book in the Harry Potter series, where Harry learns the truth about his parents' past.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Fantasy",
                            ISBN = "978-0439655484",
                            ImageUrl = "https://static.wikia.nocookie.net/harrypotter/images/3/3e/Harry-Potter-And-The-Prisoner-Of-Azkaban_novel.jpg",
                            IsAvailable = false,
                            Language = "English",
                            Location = "Shelf 2, Row 2",
                            PageCount = 387,
                            Publisher = "Bloomsbury Publishing",
                            Tags = new List<string> { "Magic", "Wizardry", "Adventure" },
                            Title = "Harry Potter and the Prisoner of Azkaban",
                            UpdatedDate = new DateTime(2023, 3, 11, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 2000
                        },
                        new
                        {
                            Id = 4,
                            Author = "J.R.R. Tolkien",
                            AverageRating = 0.80000000000000004,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 6, 22, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "The first book in the Lord of the Rings series, where a young hobbit embarks on a perilous journey.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Fantasy",
                            ISBN = "978-0547928210",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/8e/The_Fellowship_of_the_Ring_cover.gif",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 2, Row 9",
                            PageCount = 363,
                            Publisher = "Houghton Mifflin",
                            Tags = new List<string> { "Fantasy", "Adventure" },
                            Title = "The Fellowship of the Ring",
                            UpdatedDate = new DateTime(2023, 8, 25, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1954
                        },
                        new
                        {
                            Id = 5,
                            Author = "J.R.R. Tolkien",
                            AverageRating = 1.8,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 9, 29, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "The second book in the Lord of the Rings series, where the fellowship faces new challenges.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Fantasy",
                            ISBN = "978-0547928203",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a1/The_Two_Towers_cover.gif",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 2, Row 10",
                            PageCount = 357,
                            Publisher = "Houghton Mifflin",
                            Tags = new List<string> { "Fantasy", "Adventure" },
                            Title = "The Two Towers",
                            UpdatedDate = new DateTime(2023, 3, 13, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1954
                        },
                        new
                        {
                            Id = 6,
                            Author = "J.R.R. Tolkien",
                            AverageRating = 3.2000000000000002,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 6, 17, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "The final book in the Lord of the Rings series, where the fate of Middle-earth is decided.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Fantasy",
                            ISBN = "978-0547928197",
                            ImageUrl = "https://en.wikipedia.org/wiki/The_Return_of_the_King#/media/File:The_Return_of_the_King_cover.gif",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 5, Row 5",
                            PageCount = 392,
                            Publisher = "Houghton Mifflin",
                            Tags = new List<string> { "Fantasy", "Adventure" },
                            Title = "The Return of the King",
                            UpdatedDate = new DateTime(2022, 12, 29, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1955
                        },
                        new
                        {
                            Id = 7,
                            Author = "Jane Austen",
                            AverageRating = 2.1000000000000001,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 6, 7, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A classic novel about love, class, and societal expectations in 19th-century England.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Classics",
                            ISBN = "978-1613823701",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/1/17/PrideAndPrejudiceTitlePage.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 6, Row 10",
                            PageCount = 372,
                            Publisher = "T. Egerton, Whitehall",
                            Tags = new List<string> { "Classics", "Romance" },
                            Title = "Pride and Prejudice",
                            UpdatedDate = new DateTime(2023, 5, 15, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1813
                        },
                        new
                        {
                            Id = 8,
                            Author = "Herman Melville",
                            AverageRating = 1.2,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 1, 7, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "An epic novel about Captain Ahab's relentless pursuit of the white whale, Moby-Dick.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Classics",
                            ISBN = "978-0553213119",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/3/36/Moby-Dick_FE_title_page.jpg",
                            IsAvailable = false,
                            Language = "English",
                            Location = "Shelf 5, Row 11",
                            PageCount = 570,
                            Publisher = "Harper & Brothers, New York",
                            Tags = new List<string> { "Classics", "Adventure" },
                            Title = "Moby-Dick",
                            UpdatedDate = new DateTime(2023, 7, 12, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1851
                        },
                        new
                        {
                            Id = 9,
                            Author = "Mary Shelley",
                            AverageRating = 0.69999999999999996,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2022, 10, 5, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A Gothic novel about the creation of a creature and the consequences of playing with nature.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Classics",
                            ISBN = "978-0486282114",
                            ImageUrl = "https://m.media-amazon.com/images/I/81F6mF9efaL._SL1500_.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 2, Row 15",
                            PageCount = 255,
                            Publisher = "Lackington, Hughes, Harding, Mavor & Jones",
                            Tags = new List<string> { "Classics", "Gothic" },
                            Title = "Frankenstein",
                            UpdatedDate = new DateTime(2023, 3, 14, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1818
                        },
                        new
                        {
                            Id = 10,
                            Author = "J.R.R. Tolkien",
                            AverageRating = 2.1000000000000001,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 1, 30, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A collection of mythopoeic tales that form the backstory to J.R.R. Tolkien's legendarium, including the creation of Middle-earth and the struggles of its inhabitants.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Fantasy",
                            ISBN = "978-0618391110",
                            ImageUrl = "https://m.media-amazon.com/images/I/51h8UkK-w8L._SL1024_.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 6, Row 13",
                            PageCount = 393,
                            Publisher = "Houghton Mifflin",
                            Tags = new List<string> { "Fantasy", "Mythology" },
                            Title = "The Silmarillion",
                            UpdatedDate = new DateTime(2023, 7, 2, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1977
                        },
                        new
                        {
                            Id = 11,
                            Author = "J.D. Salinger",
                            AverageRating = 0.69999999999999996,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 2, 25, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A coming-of-age novel that explores the alienation and disillusionment of a young man in New York City.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Fiction",
                            ISBN = "978-0316769488",
                            ImageUrl = "https://m.media-amazon.com/images/I/81W0hu9MrQL._SL1500_.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 1, Row 9",
                            PageCount = 268,
                            Publisher = "Little, Brown and Company",
                            Tags = new List<string> { "Fiction", "Coming of Age" },
                            Title = "The Catcher in the Rye",
                            UpdatedDate = new DateTime(2023, 4, 18, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1951
                        },
                        new
                        {
                            Id = 12,
                            Author = "Herman Melville",
                            AverageRating = 4.9000000000000004,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2022, 11, 6, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A novel that tells the epic tale of Captain Ahab's obsession with a giant white whale, Moby-Dick.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Classics",
                            ISBN = "978-0142437247",
                            ImageUrl = "https://m.media-amazon.com/images/I/51G2T2elJ6L._SL1000_.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 2, Row 15",
                            PageCount = 404,
                            Publisher = "Harper & Brothers",
                            Tags = new List<string> { "Classics", "Adventure" },
                            Title = "Moby-Dick",
                            UpdatedDate = new DateTime(2023, 9, 10, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1851
                        },
                        new
                        {
                            Id = 13,
                            Author = "F. Scott Fitzgerald",
                            AverageRating = 4.5999999999999996,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 1, 2, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A novel set in the Roaring Twenties, exploring themes of wealth, love, and the American Dream.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Fiction",
                            ISBN = "978-0743273565",
                            ImageUrl = "https://m.media-amazon.com/images/I/51o3F7CdtpL._SL1051_.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 9, Row 15",
                            PageCount = 241,
                            Publisher = "Charles Scribner's Sons",
                            Tags = new List<string> { "Fiction", "Classic" },
                            Title = "The Great Gatsby",
                            UpdatedDate = new DateTime(2023, 6, 11, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1925
                        },
                        new
                        {
                            Id = 14,
                            Author = "J.R.R. Tolkien",
                            AverageRating = 2.2000000000000002,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 9, 2, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A beloved fantasy novel about the adventures of Bilbo Baggins, a hobbit who sets out on a quest.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Fantasy",
                            ISBN = "978-0547928227",
                            ImageUrl = "https://m.media-amazon.com/images/I/71p3j4p9a3L._SL1500_.jpg",
                            IsAvailable = false,
                            Language = "English",
                            Location = "Shelf 1, Row 14",
                            PageCount = 228,
                            Publisher = "George Allen & Unwin",
                            Tags = new List<string> { "Fantasy", "Adventure" },
                            Title = "The Hobbit",
                            UpdatedDate = new DateTime(2023, 2, 11, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1937
                        },
                        new
                        {
                            Id = 15,
                            Author = "William Golding",
                            AverageRating = 1.5,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 2, 10, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A novel about a group of boys stranded on an uninhabited island and their descent into chaos.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Fiction",
                            ISBN = "978-0143124290",
                            ImageUrl = "https://m.media-amazon.com/images/I/91C0SiJ7mxL._SL1500_.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 1, Row 16",
                            PageCount = 245,
                            Publisher = "Faber and Faber",
                            Tags = new List<string> { "Fiction", "Classic" },
                            Title = "The Lord of the Flies",
                            UpdatedDate = new DateTime(2023, 8, 24, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1954
                        },
                        new
                        {
                            Id = 16,
                            Author = "Aldous Huxley",
                            AverageRating = 2.2000000000000002,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 8, 16, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A dystopian novel that explores a futuristic society driven by technological advancement and control.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Science Fiction",
                            ISBN = "978-0060850524",
                            ImageUrl = "https://m.media-amazon.com/images/I/51oIvzjqQrL._SL1200_.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 8, Row 4",
                            PageCount = 222,
                            Publisher = "Chatto & Windus",
                            Tags = new List<string> { "Science Fiction", "Dystopian" },
                            Title = "Brave New World",
                            UpdatedDate = new DateTime(2023, 6, 16, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1932
                        },
                        new
                        {
                            Id = 17,
                            Author = "Ben Lerner",
                            AverageRating = 1.8,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2022, 12, 27, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A novel about a writer in Brooklyn who is asked to write a book about art and time.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Fiction",
                            ISBN = "978-0571322479",
                            ImageUrl = "https://m.media-amazon.com/images/I/71d5aTdHy7L._SL1500_.jpg",
                            IsAvailable = false,
                            Language = "English",
                            Location = "Shelf 8, Row 1",
                            PageCount = 233,
                            Publisher = "Faber & Faber",
                            Tags = new List<string> { "Fiction", "Contemporary" },
                            Title = "10:04",
                            UpdatedDate = new DateTime(2023, 4, 27, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 2014
                        },
                        new
                        {
                            Id = 18,
                            Author = "Miguel de Cervantes",
                            AverageRating = 2.8999999999999999,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 9, 16, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A satirical novel about a self-proclaimed knight, Don Quixote, and his loyal squire, Sancho Panza.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Classics",
                            ISBN = "978-0060934347",
                            ImageUrl = "https://m.media-amazon.com/images/I/91bPKTfBpkL._SL1500_.jpg",
                            IsAvailable = false,
                            Language = "Spanish",
                            Location = "Shelf 7, Row 18",
                            PageCount = 626,
                            Publisher = "Harper Perennial",
                            Tags = new List<string> { "Classics", "Satire" },
                            Title = "Don Quixote",
                            UpdatedDate = new DateTime(2023, 5, 1, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1605
                        },
                        new
                        {
                            Id = 19,
                            Author = "Leo Tolstoy",
                            AverageRating = 3.5,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 9, 14, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A historical novel that explores the lives of Russian aristocrats during the Napoleonic era.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Classics",
                            ISBN = "978-0143039990",
                            ImageUrl = "https://m.media-amazon.com/images/I/51JLT0J3JTL._SL1053_.jpg",
                            IsAvailable = false,
                            Language = "Russian",
                            Location = "Shelf 8, Row 17",
                            PageCount = 825,
                            Publisher = "Penguin Classics",
                            Tags = new List<string> { "Classics", "Historical Fiction" },
                            Title = "War and Peace",
                            UpdatedDate = new DateTime(2023, 1, 23, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1866
                        },
                        new
                        {
                            Id = 20,
                            Author = "Ben Lerner",
                            AverageRating = 0.90000000000000002,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 2, 10, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A novel about an American poet in Madrid, exploring themes of authenticity and alienation.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Fiction",
                            ISBN = "978-1566892748",
                            ImageUrl = "https://m.media-amazon.com/images/I/81FQ7jutv8L._SL1500_.jpg",
                            IsAvailable = false,
                            Language = "English",
                            Location = "Shelf 9, Row 11",
                            PageCount = 176,
                            Publisher = "Coffee House Press",
                            Tags = new List<string> { "Fiction", "Literary" },
                            Title = "Leaving the Atocha Station",
                            UpdatedDate = new DateTime(2022, 11, 10, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 2010
                        },
                        new
                        {
                            Id = 21,
                            Author = "Cormac McCarthy",
                            AverageRating = 3.7000000000000002,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 4, 14, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A post-apocalyptic novel following a father and son's journey in a desolate and dangerous world.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Fiction",
                            ISBN = "978-0307387899",
                            ImageUrl = "https://m.media-amazon.com/images/I/81iB+fUN2yL._SL1500_.jpg",
                            IsAvailable = false,
                            Language = "English",
                            Location = "Shelf 4, Row 19",
                            PageCount = 271,
                            Publisher = "Vintage",
                            Tags = new List<string> { "Fiction", "Post-Apocalyptic" },
                            Title = "The Road",
                            UpdatedDate = new DateTime(2022, 12, 19, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 2006
                        },
                        new
                        {
                            Id = 22,
                            Author = "Stephen King",
                            AverageRating = 0.90000000000000002,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 4, 19, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A psychological horror novel about a family's descent into madness in a haunted hotel.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Horror",
                            ISBN = "978-0345806789",
                            ImageUrl = "https://m.media-amazon.com/images/I/71aRkaY7gqL._SL1500_.jpg",
                            IsAvailable = false,
                            Language = "English",
                            Location = "Shelf 3, Row 3",
                            PageCount = 490,
                            Publisher = "Anchor",
                            Tags = new List<string> { "Horror", "Psychological" },
                            Title = "The Shining",
                            UpdatedDate = new DateTime(2023, 5, 10, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1977
                        },
                        new
                        {
                            Id = 23,
                            Author = "C.S. Lewis",
                            AverageRating = 0.0,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 4, 26, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "The first book in the classic fantasy series, where four siblings discover a magical world through a wardrobe.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Fantasy",
                            ISBN = "978-0060764890",
                            ImageUrl = "https://m.media-amazon.com/images/I/71JSzS8STJL._SL1080_.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 8, Row 14",
                            PageCount = 223,
                            Publisher = "HarperCollins",
                            Tags = new List<string> { "Fantasy", "Adventure" },
                            Title = "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
                            UpdatedDate = new DateTime(2022, 10, 17, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1950
                        },
                        new
                        {
                            Id = 24,
                            Author = "Harper Lee",
                            AverageRating = 0.69999999999999996,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 4, 18, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A powerful novel that addresses issues of racism and injustice in the American South.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Classics",
                            ISBN = "978-0061120084",
                            ImageUrl = "https://m.media-amazon.com/images/I/81mc4QUQx1L._SL1500_.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 4, Row 7",
                            PageCount = 371,
                            Publisher = "Harper Perennial Modern Classics",
                            Tags = new List<string> { "Classics", "Social Issues" },
                            Title = "To Kill a Mockingbird",
                            UpdatedDate = new DateTime(2023, 6, 15, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1960
                        },
                        new
                        {
                            Id = 25,
                            Author = "George Orwell",
                            AverageRating = 1.3,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 7, 4, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A dystopian novel that portrays a totalitarian society and the dangers of totalitarianism.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Classics",
                            ISBN = "978-0451524935",
                            ImageUrl = "https://m.media-amazon.com/images/I/81hb+PE4PrL._SL1500_.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 6, Row 12",
                            PageCount = 303,
                            Publisher = "Signet Classic",
                            Tags = new List<string> { "Classics", "Dystopian" },
                            Title = "1984",
                            UpdatedDate = new DateTime(2023, 2, 9, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1949
                        },
                        new
                        {
                            Id = 26,
                            Author = "Frank Herbert",
                            AverageRating = 2.7999999999999998,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 6, 21, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A science fiction epic set on the desert planet of Arrakis, where a young hero rises to power.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Science Fiction",
                            ISBN = "978-0441013593",
                            ImageUrl = "https://m.media-amazon.com/images/I/81PbvmCKLWL._SL1500_.jpg",
                            IsAvailable = false,
                            Language = "English",
                            Location = "Shelf 8, Row 13",
                            PageCount = 523,
                            Publisher = "Ace Books",
                            Tags = new List<string> { "Science Fiction", "Adventure" },
                            Title = "Dune",
                            UpdatedDate = new DateTime(2023, 6, 15, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 1965
                        },
                        new
                        {
                            Id = 27,
                            Author = "Stieg Larsson",
                            AverageRating = 2.2000000000000002,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 6, 22, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A gripping mystery novel involving a journalist and a hacker in a cold case investigation.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Mystery",
                            ISBN = "978-0307269751",
                            ImageUrl = "https://m.media-amazon.com/images/I/81kAd8kZvOL._SL1500_.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 8, Row 15",
                            PageCount = 414,
                            Publisher = "Knopf",
                            Tags = new List<string> { "Mystery", "Thriller" },
                            Title = "The Girl with the Dragon Tattoo",
                            UpdatedDate = new DateTime(2022, 11, 16, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 2005
                        },
                        new
                        {
                            Id = 28,
                            Author = "Anthony Doerr",
                            AverageRating = 3.5,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 3, 31, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A beautifully written historical novel that weaves together the lives of a blind French girl and a German boy during World War II.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Historical Fiction",
                            ISBN = "978-1501173219",
                            ImageUrl = "https://m.media-amazon.com/images/I/81RkLxFbQfL._SL1500_.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 8, Row 16",
                            PageCount = 351,
                            Publisher = "Scribner",
                            Tags = new List<string> { "Historical Fiction", "World War II" },
                            Title = "All the Light We Cannot See",
                            UpdatedDate = new DateTime(2023, 4, 1, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 2013
                        },
                        new
                        {
                            Id = 29,
                            Author = "Patrick Rothfuss",
                            AverageRating = 1.6000000000000001,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 1, 31, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "The first book in the Kingkiller Chronicle series, following the life and adventures of the gifted musician and magician Kvothe.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Fantasy",
                            ISBN = "978-0756404741",
                            ImageUrl = "https://m.media-amazon.com/images/I/71gYfSWWB6L._SL1200_.jpg",
                            IsAvailable = false,
                            Language = "English",
                            Location = "Shelf 4, Row 7",
                            PageCount = 768,
                            Publisher = "DAW Books",
                            Tags = new List<string> { "Fantasy", "Adventure" },
                            Title = "The Name of the Wind",
                            UpdatedDate = new DateTime(2023, 7, 9, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 2007
                        },
                        new
                        {
                            Id = 30,
                            Author = "Yuval Noah Harari",
                            AverageRating = 2.6000000000000001,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 9, 24, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Description = "A thought-provoking exploration of the history and impact of Homo sapiens on the world.",
                            DueDate = new DateTime(2023, 10, 3, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            Genre = "Non-Fiction",
                            ISBN = "978-0062316097",
                            ImageUrl = "https://m.media-amazon.com/images/I/51y5lwnN5+L._SL160_.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 1, Row 16",
                            PageCount = 474,
                            Publisher = "Harper",
                            Tags = new List<string> { "Non-Fiction", "History" },
                            Title = "Sapiens: A Brief History of Humankind",
                            UpdatedDate = new DateTime(2022, 10, 12, 21, 50, 28, 597, DateTimeKind.Utc).AddTicks(8448),
                            YearPublished = 2011
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
