// <auto-generated />
using System;
using System.Collections.Generic;
using Library_BookAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Library_BookAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231003204057_addBookTable")]
    partial class addBookTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Library_BookAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<string>("Borrower")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YearPublished")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J.K. Rowling",
                            AverageRating = 4.5,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 9, 25, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Description = "The first book in the Harry Potter series, where young Harry discovers his magical heritage.",
                            DueDate = new DateTime(2023, 10, 3, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Genre = "Fantasy",
                            ISBN = "978-0747532743",
                            ImageUrl = "https://m.media-amazon.com/images/I/91AbRwk2S0L._SL1500_.jpg",
                            IsAvailable = false,
                            Language = "English",
                            Location = "Shelf 9, Row 19",
                            PageCount = 251,
                            Publisher = "Bloomsbury Publishing",
                            Tags = new List<string> { "Magic", "Wizardry", "Adventure" },
                            Title = "Harry Potter and the Philosopher's Stone",
                            UpdatedDate = new DateTime(2022, 12, 8, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            YearPublished = 1997
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.K. Rowling",
                            AverageRating = 1.6000000000000001,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 5, 4, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Description = "The second book in the Harry Potter series, where Harry returns to Hogwarts amidst mysterious attacks.",
                            DueDate = new DateTime(2023, 10, 3, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Genre = "Fantasy",
                            ISBN = "978-0439064873",
                            ImageUrl = "https://static.wikia.nocookie.net/harrypotter/images/1/17/Chamberofsecrets.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 6, Row 15",
                            PageCount = 389,
                            Publisher = "Bloomsbury Publishing",
                            Tags = new List<string> { "Magic", "Wizardry", "Adventure" },
                            Title = "Harry Potter and the Chamber of Secrets",
                            UpdatedDate = new DateTime(2023, 3, 6, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            YearPublished = 1999
                        },
                        new
                        {
                            Id = 3,
                            Author = "J.K. Rowling",
                            AverageRating = 0.80000000000000004,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 1, 21, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Description = "The third book in the Harry Potter series, where Harry learns the truth about his parents' past.",
                            DueDate = new DateTime(2023, 10, 3, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Genre = "Fantasy",
                            ISBN = "978-0439655484",
                            ImageUrl = "https://static.wikia.nocookie.net/harrypotter/images/3/3e/Harry-Potter-And-The-Prisoner-Of-Azkaban_novel.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 3, Row 14",
                            PageCount = 352,
                            Publisher = "Bloomsbury Publishing",
                            Tags = new List<string> { "Magic", "Wizardry", "Adventure" },
                            Title = "Harry Potter and the Prisoner of Azkaban",
                            UpdatedDate = new DateTime(2022, 12, 20, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            YearPublished = 1999
                        },
                        new
                        {
                            Id = 4,
                            Author = "J.R.R. Tolkien",
                            AverageRating = 3.1000000000000001,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 7, 12, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Description = "The first book in the Lord of the Rings series, where a young hobbit embarks on a perilous journey.",
                            DueDate = new DateTime(2023, 10, 3, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Genre = "Fantasy",
                            ISBN = "978-0547928210",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/8e/The_Fellowship_of_the_Ring_cover.gif",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 3, Row 10",
                            PageCount = 400,
                            Publisher = "Houghton Mifflin",
                            Tags = new List<string> { "Fantasy", "Adventure" },
                            Title = "The Fellowship of the Ring",
                            UpdatedDate = new DateTime(2023, 5, 19, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            YearPublished = 1954
                        },
                        new
                        {
                            Id = 5,
                            Author = "J.R.R. Tolkien",
                            AverageRating = 1.5,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2022, 10, 26, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Description = "The second book in the Lord of the Rings series, where the fellowship faces new challenges.",
                            DueDate = new DateTime(2023, 10, 3, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Genre = "Fantasy",
                            ISBN = "978-0547928203",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a1/The_Two_Towers_cover.gif",
                            IsAvailable = false,
                            Language = "English",
                            Location = "Shelf 1, Row 18",
                            PageCount = 380,
                            Publisher = "Houghton Mifflin",
                            Tags = new List<string> { "Fantasy", "Adventure" },
                            Title = "The Two Towers",
                            UpdatedDate = new DateTime(2022, 12, 8, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            YearPublished = 1954
                        },
                        new
                        {
                            Id = 6,
                            Author = "J.R.R. Tolkien",
                            AverageRating = 2.5,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2022, 12, 22, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Description = "The final book in the Lord of the Rings series, where the fate of Middle-earth is decided.",
                            DueDate = new DateTime(2023, 10, 3, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Genre = "Fantasy",
                            ISBN = "978-0547928197",
                            ImageUrl = "https://en.wikipedia.org/wiki/The_Return_of_the_King#/media/File:The_Return_of_the_King_cover.gif",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 5, Row 4",
                            PageCount = 305,
                            Publisher = "Houghton Mifflin",
                            Tags = new List<string> { "Fantasy", "Adventure" },
                            Title = "The Return of the King",
                            UpdatedDate = new DateTime(2022, 11, 11, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            YearPublished = 1955
                        },
                        new
                        {
                            Id = 7,
                            Author = "Jane Austen",
                            AverageRating = 4.5999999999999996,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2022, 12, 6, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Description = "A classic novel about love, class, and societal expectations in 19th-century England.",
                            DueDate = new DateTime(2023, 10, 3, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Genre = "Classics",
                            ISBN = "978-1613823701",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/1/17/PrideAndPrejudiceTitlePage.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 9, Row 8",
                            PageCount = 261,
                            Publisher = "T. Egerton, Whitehall",
                            Tags = new List<string> { "Classics", "Romance" },
                            Title = "Pride and Prejudice",
                            UpdatedDate = new DateTime(2022, 12, 3, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            YearPublished = 1813
                        },
                        new
                        {
                            Id = 8,
                            Author = "Herman Melville",
                            AverageRating = 0.5,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2022, 12, 20, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Description = "An epic novel about Captain Ahab's relentless pursuit of the white whale, Moby-Dick.",
                            DueDate = new DateTime(2023, 10, 3, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Genre = "Classics",
                            ISBN = "978-0553213119",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/3/36/Moby-Dick_FE_title_page.jpg",
                            IsAvailable = true,
                            Language = "English",
                            Location = "Shelf 6, Row 5",
                            PageCount = 419,
                            Publisher = "Harper & Brothers, New York",
                            Tags = new List<string> { "Classics", "Adventure" },
                            Title = "Moby-Dick",
                            UpdatedDate = new DateTime(2023, 8, 30, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            YearPublished = 1851
                        },
                        new
                        {
                            Id = 9,
                            Author = "Mary Shelley",
                            AverageRating = 1.2,
                            Borrower = "N/A",
                            CreatedDate = new DateTime(2023, 9, 2, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Description = "A Gothic novel about the creation of a creature and the consequences of playing with nature.",
                            DueDate = new DateTime(2023, 10, 3, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            Genre = "Classics",
                            ISBN = "978-0486282114",
                            ImageUrl = "https://m.media-amazon.com/images/I/81F6mF9efaL._SL1500_.jpg",
                            IsAvailable = false,
                            Language = "English",
                            Location = "Shelf 3, Row 5",
                            PageCount = 342,
                            Publisher = "Lackington, Hughes, Harding, Mavor & Jones",
                            Tags = new List<string> { "Classics", "Gothic" },
                            Title = "Frankenstein",
                            UpdatedDate = new DateTime(2023, 2, 21, 20, 40, 56, 951, DateTimeKind.Utc).AddTicks(6944),
                            YearPublished = 1818
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
